### ISSUE TITLE
NoMethodError in TodoItemsController#new

### ISSUE THREAD

**Issue by kouess6** [jhu-ep-coursera/fullstack-course2-module4-i-reviewed#1]
NoMethodError in TodoItemsController#new
undefined method `todo_items' for nil:NilClass
Extracted source (around line #12):

  # GET /todo_list/:todo_list_id/todo_items/new
  def new
    _**@todo_item = @todo_list.todo_items.new**_

  end

Rails.root: /home/vm/dockerdoc/course2_module4/todolists
Application Trace | Framework Trace | Full Trace

app/controllers/todo_items_controller.rb:12:in `new'

Request

Parameters:

{"todo_list_id"=>"547"}

I can see that the params todo_list_id is passed, but it doesn't create the TodoList object.
This is my code in TodoItems controller:
 before_action  :set_todo_list, :set_todo_item, only: [:show, :edit, :update, :destroy]
def new
    @todo_item = @todo_list.todo_items.new
  end

 private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:title, :due_date, :description, :completed)
    end

    #Set TodoList via TodoItem Controller
    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

And the route.rb file:

Rails.application.routes.draw do
  root to: "todo_lists#index"
  resources :sessions, only: [:new, :create, :destroy]

  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
  #get "/todo_lists" => "todo_lists#show", as: "todo_list"
  
  resources :users
  resources :profiles
  resources :todo_lists do
    resources :todo_items#, only: [:create, :destroy]
  end
  
I try to troubleshoot but i didn't find where is my mistake.

**Comment by kalmanh** [comment]
It looks like your `set_todo_list` method, which would create/set `@todo_list` only gets run before `:show, :edit, :update, :destroy` actions. This is why it blows up in the `new` action, since you have not initialized a `@todo_list`

**Comment by kouess6** [comment]
Hello,
Thank you for your answer,
I restarted the assignement and saw that i should instantiate @todo_list.
So i wrote:
@todo_list = set_todo_list in methods.

Now everything is okay.

**Comment by kalmanh** [comment]
👍  Great!
